version: '3.8'

services:
  mysql-master:
    image: 'bitnami/mysql:latest'
    hostname: mysql-master
    ports:
      - '3306'
    volumes:
      - ./conf/mysql/mysql-master-my.cnf:/opt/bitnami/mysql/conf/my.cnf
      - ./conf/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./conf/mysql/mysqlsampledatabase.sql:/docker-entrypoint-initdb.d/mysqlsampledatabase.sql
    environment:
      - MYSQL_REPLICATION_MODE=master
      - MYSQL_REPLICATION_USER=repl_user
      - MYSQL_REPLICATION_PASSWORD=repl_password
      - MYSQL_ROOT_PASSWORD=master_root_password
      - MYSQL_USER=my_user
      - MYSQL_PASSWORD=my_password
      - MYSQL_DATABASE=my_database
  mysql-rslave:
    image: 'bitnami/mysql:latest'
    hostname: mysql-rslave
    ports:
      - '3306'
    volumes:
      - ./conf/mysql/mysql-rslave-my.cnf:/opt/bitnami/mysql/conf/my.cnf
    depends_on:
      - mysql-master
    environment:
      - MYSQL_REPLICATION_MODE=slave
      - MYSQL_REPLICATION_USER=repl_user
      - MYSQL_REPLICATION_PASSWORD=repl_password
      - MYSQL_MASTER_HOST=mysql-master
      - MYSQL_MASTER_PORT_NUMBER=3306
      - MYSQL_MASTER_ROOT_PASSWORD=master_root_password
  mysql-bslave:
    image: 'bitnami/mysql:latest'
    hostname: mysql-bslave
    ports:
      - '3306'
    volumes:
      - ./conf/mysql/mysql-bslave-my.cnf:/opt/bitnami/mysql/conf/my.cnf
    depends_on:
      - mysql-master
    environment:
      - MYSQL_REPLICATION_MODE=slave
      - MYSQL_REPLICATION_USER=repl_user
      - MYSQL_REPLICATION_PASSWORD=repl_password
      - MYSQL_MASTER_HOST=mysql-master
      - MYSQL_MASTER_PORT_NUMBER=3306
      - MYSQL_MASTER_ROOT_PASSWORD=master_root_password
  query-exporter:
    image: adonato/query-exporter:latest
    hostname: query-exporter
    ports:
      - '9560:9560'
    volumes:
      - ./conf/query-exporter/config.yaml:/config.yaml
    depends_on:
      - mysql-master
      - mysql-rslave
      - mysql-bslave
  prometheus:
    image: prom/prometheus:latest
    hostname: prometheus
    volumes:
      - ./conf/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    ports:
      - '9090:9090'
    depends_on:
      - query-exporter
  grafana:
    image: grafana/grafana-oss:latest
    hostname: grafana
    user: "472"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./conf/grafana/provisioning:/etc/grafana/provisioning
    env_file:
      - ./conf/grafana/config.monitoring
    ports:
      - '3000:3000'
    depends_on:
      - prometheus
      - query-exporter
    
volumes:
  mysql_master_data:
    driver: local
  grafana_data: {}
  prometheus_data: {}
networks:
  default:
    name: mysql-ha
    external: true
